task:
  matrix:
    - name: FreeBSD 11
      freebsd_instance:
        image: freebsd-11-4-release-amd64
    - name: FreeBSD 12
      freebsd_instance:
        image: freebsd-12-2-release-amd64
    - name: FreeBSD 13
      freebsd_instance:
        image: freebsd-13-0-alpha3-amd64
  setup_script:
    - pkg install -y curl llvm90
    - kldload pmc
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --profile=minimal
    - . $HOME/.cargo/env
    - rustup default stable
  test_script:
    - . $HOME/.cargo/env
    - cargo test
