task:
  matrix:
    # - name: FreeBSD 11
    #   freebsd_instance:
    #     image: freebsd-11-4-release-amd64
    # - name: FreeBSD 12
    #   freebsd_instance:
    #     image: freebsd-12-2-release-amd64
    - name: FreeBSD 13
      freebsd_instance:
        image: freebsd-13-2-release-amd64

  setup_script:
    - pkg install -y llvm
    - kldload pmc
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain stable
    - . $HOME/.cargo/env
    
    # Print the state of the CPU PMCs and supported events to help with
    # debugging.
    #
    # NOTE: Cirrus seems to use Google Cloud which DOES NOT support PMCs -
    # attempting to use them returns EINVAL
    - pmccontrol -s
    - pmccontrol -L

  test_script:
    - . $HOME/.cargo/env
    - cargo test
